/*
  Generated by kison.
*/
var parser = (function(undefined) {
  /*jshint quotmark:false, loopfunc:true, indent:false, unused:false, asi:true, boss:true*/
  /* Generated by kison */
  var parser = {};
  var GrammarConst = {
    SHIFT_TYPE: 1,
    REDUCE_TYPE: 2,
    ACCEPT_TYPE: 0,
    TYPE_INDEX: 0,
    PRODUCTION_INDEX: 1,
    TO_INDEX: 2,
  };
  function peekStack(stack, n) {
    n = n || 1;
    return stack[stack.length - n];
  } /*jslint quotmark: false*/
  /*jslint quotmark: false*/
  function mix(to, from) {
    for (var f in from) {
      to[f] = from[f];
    }
  }
  function isArray(obj) {
    return '[object Array]' === Object.prototype.toString.call(obj);
  }
  function each(object, fn, context) {
    if (object) {
      var key,
        val,
        length,
        i = 0;
      context = context || null;
      if (!isArray(object)) {
        for (key in object) {
          // can not use hasOwnProperty
          if (fn.call(context, object[key], key, object) === false) {
            break;
          }
        }
      } else {
        length = object.length;
        for (val = object[0]; i < length; val = object[++i]) {
          if (fn.call(context, val, i, object) === false) {
            break;
          }
        }
      }
    }
  }
  function inArray(item, arr) {
    for (var i = 0, l = arr.length; i < l; i++) {
      if (arr[i] === item) {
        return true;
      }
    }
    return false;
  }
  var Lexer = function Lexer(cfg) {
    var self = this; /*
     lex rules.
     @type {Object[]}
     @example
     [
     {
     regexp:'\\w+',
     state:['xx'],
     token:'c',
     // this => lex
     action:function(){}
     }
     ]
     */
    /*
     lex rules.
     @type {Object[]}
     @example
     [
     {
     regexp:'\\w+',
     state:['xx'],
     token:'c',
     // this => lex
     action:function(){}
     }
     ]
     */
    self.rules = [];
    mix(self, cfg); /*
     Input languages
     @type {String}
     */
    /*
     Input languages
     @type {String}
     */
    self.resetInput(self.input);
  };
  Lexer.prototype = {
    resetInput: function(input) {
      mix(this, {
        input: input,
        matched: '',
        stateStack: [Lexer.STATIC.INITIAL],
        match: '',
        text: '',
        firstLine: 1,
        lineNumber: 1,
        lastLine: 1,
        firstColumn: 1,
        lastColumn: 1,
      });
    },
    getCurrentRules: function() {
      var self = this,
        currentState = self.stateStack[self.stateStack.length - 1],
        rules = []; //#JSCOVERAGE_IF
      //#JSCOVERAGE_IF
      if (self.mapState) {
        currentState = self.mapState(currentState);
      }
      each(self.rules, function(r) {
        var state = r.state || r[3];
        if (!state) {
          if (currentState === Lexer.STATIC.INITIAL) {
            rules.push(r);
          }
        } else if (inArray(currentState, state)) {
          rules.push(r);
        }
      });
      return rules;
    },
    pushState: function(state) {
      this.stateStack.push(state);
    },
    popState: function(num) {
      num = num || 1;
      var ret;
      while (num--) {
        ret = this.stateStack.pop();
      }
      return ret;
    },
    showDebugInfo: function() {
      var self = this,
        DEBUG_CONTEXT_LIMIT = Lexer.STATIC.DEBUG_CONTEXT_LIMIT,
        matched = self.matched,
        match = self.match,
        input = self.input;
      matched = matched.slice(0, matched.length - match.length); //#JSCOVERAGE_IF 0
      //#JSCOVERAGE_IF 0
      var past =
          (matched.length > DEBUG_CONTEXT_LIMIT ? '...' : '') +
          matched.slice(0 - DEBUG_CONTEXT_LIMIT).replace(/\n/g, ' '),
        next = match + input; //#JSCOVERAGE_ENDIF
      //#JSCOVERAGE_ENDIF
      next =
        next.slice(0, DEBUG_CONTEXT_LIMIT).replace(/\n/g, ' ') +
        (next.length > DEBUG_CONTEXT_LIMIT ? '...' : '');
      return past + next + '\n' + new Array(past.length + 1).join('-') + '^';
    },
    mapSymbol: function mapSymbolForCodeGen(t) {
      return this.symbolMap[t];
    },
    mapReverseSymbol: function(rs) {
      var self = this,
        symbolMap = self.symbolMap,
        i,
        reverseSymbolMap = self.reverseSymbolMap;
      if (!reverseSymbolMap && symbolMap) {
        reverseSymbolMap = self.reverseSymbolMap = {};
        for (i in symbolMap) {
          reverseSymbolMap[symbolMap[i]] = i;
        }
      } //#JSCOVERAGE_IF
      //#JSCOVERAGE_IF
      if (reverseSymbolMap) {
        return reverseSymbolMap[rs];
      } else {
        return rs;
      }
    },
    lex: function() {
      var self = this,
        input = self.input,
        i,
        rule,
        m,
        ret,
        lines,
        rules = self.getCurrentRules();
      self.match = self.text = '';
      if (!input) {
        return self.mapSymbol(Lexer.STATIC.END_TAG);
      }
      for (i = 0; i < rules.length; i++) {
        rule = rules[i]; //#JSCOVERAGE_IF 0
        //#JSCOVERAGE_IF 0
        var regexp = rule.regexp || rule[1],
          token = rule.token || rule[0],
          action = rule.action || rule[2] || undefined; //#JSCOVERAGE_ENDIF
        //#JSCOVERAGE_ENDIF
        if ((m = input.match(regexp))) {
          lines = m[0].match(/\n.*/g);
          if (lines) {
            self.lineNumber += lines.length;
          }
          mix(self, {
            firstLine: self.lastLine,
            lastLine: self.lineNumber,
            firstColumn: self.lastColumn,
            lastColumn: lines
              ? lines[lines.length - 1].length - 1
              : self.lastColumn + m[0].length,
          });
          var match; // for error report
          // for error report
          match = self.match = m[0]; // all matches
          // all matches
          self.matches = m; // may change by user
          // may change by user
          self.text = match; // matched content utils now
          // matched content utils now
          self.matched += match;
          ret = action && action.call(self);
          if (ret === undefined) {
            ret = token;
          } else {
            ret = self.mapSymbol(ret);
          }
          input = input.slice(match.length);
          self.input = input;
          if (ret) {
            return ret;
          } else {
            // ignore
            return self.lex();
          }
        }
      }
    },
  };
  Lexer.STATIC = {
    INITIAL: 'I',
    DEBUG_CONTEXT_LIMIT: 20,
    END_TAG: '$EOF',
  };
  var lexer = new Lexer({
    rules: [
      [
        0,
        /^[\s\S]*?(?={{)/,
        function() {
          var self = this,
            text = self.text,
            m,
            n = 0;
          if ((m = text.match(/\\+$/))) {
            n = m[0].length;
          }
          if (n % 2) {
            self.pushState('et');
            text = text.slice(0, -1);
          } else {
            self.pushState('t');
          }
          if (n) {
            text = text.replace(/\\+$/g, function(m) {
              return new Array(m.length / 2 + 1).join('\\');
            });
          } // https://github.com/kissyteam/kissy/issues/330
          // return even empty
          // https://github.com/kissyteam/kissy/issues/330
          // return even empty
          self.text = text;
          return 'CONTENT';
        },
      ],
      ['b', /^[\s\S]+/, 0],
      [
        'b',
        /^[\s\S]{2,}?(?:(?={{)|$)/,
        function popState() {
          this.popState();
        },
        ['et'],
      ],
      [
        'c',
        /^{{\{?~?(?:#|@)/,
        function() {
          var self = this,
            text = self.text;
          if (text.slice(0, 3) === '{{{') {
            self.pushState('p');
          } else {
            self.pushState('e');
          }
        },
        ['t'],
      ],
      [
        'd',
        /^{{\{?~?\//,
        function() {
          var self = this,
            text = self.text;
          if (text.slice(0, 3) === '{{{') {
            self.pushState('p');
          } else {
            self.pushState('e');
          }
        },
        ['t'],
      ],
      [
        'e',
        /^{{\s*else\s*}}/,
        function popState() {
          this.popState();
        },
        ['t'],
      ],
      [
        0,
        /^{{![\s\S]*?}}/,
        function popState() {
          this.popState();
        },
        ['t'],
      ],
      [
        'b',
        /^{{%([\s\S]*?)%}}/,
        function() {
          // return to content mode
          this.text = this.matches[1] || '';
          this.popState();
        },
        ['t'],
      ],
      [
        'f',
        /^{{\{?~?/,
        function() {
          var self = this,
            text = self.text;
          if (text.slice(0, 3) === '{{{') {
            self.pushState('p');
          } else {
            self.pushState('e');
          }
        },
        ['t'],
      ],
      [0, /^\s+/, 0, ['p', 'e']],
      ['g', /^,/, 0, ['p', 'e']],
      [
        'h',
        /^~?}}}/,
        function() {
          this.popState(2);
        },
        ['p'],
      ],
      [
        'h',
        /^~?}}/,
        function() {
          this.popState(2);
        },
        ['e'],
      ],
      ['i', /^\(/, 0, ['p', 'e']],
      ['j', /^\)/, 0, ['p', 'e']],
      ['k', /^\|\|/, 0, ['p', 'e']],
      ['l', /^&&/, 0, ['p', 'e']],
      ['m', /^===/, 0, ['p', 'e']],
      ['n', /^!==/, 0, ['p', 'e']],
      ['o', /^>=/, 0, ['p', 'e']],
      ['p', /^<=/, 0, ['p', 'e']],
      ['q', /^>/, 0, ['p', 'e']],
      ['r', /^</, 0, ['p', 'e']],
      ['s', /^\+/, 0, ['p', 'e']],
      ['t', /^-/, 0, ['p', 'e']],
      ['u', /^\*/, 0, ['p', 'e']],
      ['v', /^\//, 0, ['p', 'e']],
      ['w', /^%/, 0, ['p', 'e']],
      ['x', /^!/, 0, ['p', 'e']],
      [
        'y',
        /^"(\\[\s\S]|[^\\"\n])*"/,
        function() {
          this.text = this.text.slice(1, -1).replace(/\\"/g, '"');
        },
        ['p', 'e'],
      ],
      [
        'y',
        /^'(\\[\s\S]|[^\\'\n])*'/,
        function() {
          this.text = this.text.slice(1, -1).replace(/\\'/g, "'");
        },
        ['p', 'e'],
      ],
      ['z', /^\d+(?:\.\d+)?(?:e-?\d+)?/i, 0, ['p', 'e']],
      ['aa', /^=/, 0, ['p', 'e']],
      [
        'ab',
        /^\.\./,
        function() {
          // wait for '/'
          this.pushState('ws');
        },
        ['p', 'e'],
      ],
      [
        'ac',
        /^\//,
        function popState() {
          this.popState();
        },
        ['ws'],
      ],
      ['ac', /^\./, 0, ['p', 'e']],
      ['ad', /^\[/, 0, ['p', 'e']],
      ['ae', /^\]/, 0, ['p', 'e']],
      ['af', /^\{/, 0, ['p', 'e']],
      ['ag', /^\:/, 0, ['p', 'e']],
      ['ah', /^\?/, 0, ['p', 'e']],
      ['ai', /^\}/, 0, ['p', 'e']],
      ['ab', /^[a-zA-Z_$][a-zA-Z0-9_$]*/, 0, ['p', 'e']],
    ],
  });
  parser.lexer = lexer;
  lexer.symbolMap = {
    $EOF: 'a',
    CONTENT: 'b',
    OPEN_BLOCK: 'c',
    OPEN_CLOSE_BLOCK: 'd',
    INVERSE: 'e',
    OPEN_TPL: 'f',
    COMMA: 'g',
    CLOSE: 'h',
    L_PAREN: 'i',
    R_PAREN: 'j',
    OR: 'k',
    AND: 'l',
    LOGIC_EQUALS: 'm',
    LOGIC_NOT_EQUALS: 'n',
    GE: 'o',
    LE: 'p',
    GT: 'q',
    LT: 'r',
    PLUS: 's',
    MINUS: 't',
    MULTIPLY: 'u',
    DIVIDE: 'v',
    MODULUS: 'w',
    NOT: 'x',
    STRING: 'y',
    NUMBER: 'z',
    EQUALS: 'aa',
    ID: 'ab',
    SEP: 'ac',
    L_BRACKET: 'ad',
    R_BRACKET: 'ae',
    L_BRACE: 'af',
    COLON: 'ag',
    QUERY: 'ah',
    R_BRACE: 'ai',
    $START: 'aj',
    program: 'ak',
    statements: 'al',
    statement: 'am',
    function: 'an',
    id: 'ao',
    expression: 'ap',
    params: 'aq',
    hash: 'ar',
    param: 'as',
    conditionalExpression: 'at',
    listExpression: 'au',
    objectExpression: 'av',
    objectPart: 'aw',
    conditionalOrExpression: 'ax',
    conditionalAndExpression: 'ay',
    equalityExpression: 'az',
    relationalExpression: 'ba',
    additiveExpression: 'bb',
    multiplicativeExpression: 'bc',
    unaryExpression: 'bd',
    primaryExpression: 'be',
    hashSegment: 'bf',
    idSegments: 'bg',
  };
  parser.productions = [
    ['aj', ['ak']],
    [
      'ak',
      ['al', 'e', 'al'],
      function() {
        return new this.yy.ProgramNode(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
          this.$3,
        );
      },
    ],
    [
      'ak',
      ['al'],
      function() {
        return new this.yy.ProgramNode(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
        );
      },
    ],
    [
      'al',
      ['am'],
      function() {
        return [this.$1];
      },
    ],
    [
      'al',
      ['al', 'am'],
      function() {
        var statements = this.$1;
        var statement = this.$2;
        if (statements.length) {
          var lastStatement = statements[statements.length - 1];
          if (
            lastStatement.rtrim &&
            statement &&
            statement.type === 'contentStatement' &&
            !statement.value.trim()
          ) {
          } else if (
            statement.ltrim &&
            lastStatement &&
            lastStatement.type === 'contentStatement' &&
            !lastStatement.value.trim()
          ) {
            statements[statements.length - 1] = statement;
          } else {
            statements.push(statement);
          }
        } else {
          statements.push(statement);
        }
      },
    ],
    [
      'am',
      ['c', 'an', 'h', 'ak', 'd', 'ao', 'h'],
      function() {
        var program = this.$4;
        var openBlock = this.$1;
        var lastClose = this.$7;
        var statements = program.statements;
        var close = this.$3;
        var openCloseBlock = this.$5;
        if (
          close.indexOf('~}') !== -1 &&
          statements[0] &&
          statements[0].type === 'contentStatement'
        ) {
          if (!statements[0].value.trim()) {
            statements.shift();
          }
        }
        if (
          openCloseBlock.indexOf('{~') !== -1 &&
          statements[statements.length - 1] &&
          statements[statements.length - 1].type === 'contentStatement'
        ) {
          if (!statements[statements.length - 1].value.trim()) {
            statements.pop();
          }
        }
        var statement = new this.yy.BlockStatement(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$2,
          program,
          this.$6,
          this.$1.slice(0, 3) !== '{{{',
        );
        if (openBlock.indexOf('{~') !== -1) {
          statement.ltrim = 1;
        }
        if (lastClose.indexOf('~}') !== -1) {
          statement.rtrim = 1;
        }
        return statement;
      },
    ],
    [
      'am',
      ['f', 'ap', 'h'],
      function() {
        var openTpl = this.$1;
        var close = this.$3;
        var statement = new this.yy.ExpressionStatement(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$2,
          this.$1.slice(0, 3) !== '{{{',
        );
        if (openTpl.indexOf('{~') !== -1) {
          statement.ltrim = 1;
        }
        if (close.indexOf('~}') !== -1) {
          statement.rtrim = 1;
        }
        return statement;
      },
    ],
    [
      'am',
      ['b'],
      function() {
        return new this.yy.ContentStatement(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
        );
      },
    ],
    [
      'an',
      ['ao', 'i', 'aq', 'g', 'ar', 'j'],
      function() {
        return new this.yy.Function(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
          this.$3,
          this.$5,
        );
      },
    ],
    [
      'an',
      ['ao', 'i', 'aq', 'j'],
      function() {
        return new this.yy.Function(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
          this.$3,
        );
      },
    ],
    [
      'an',
      ['ao', 'i', 'ar', 'j'],
      function() {
        return new this.yy.Function(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
          null,
          this.$3,
        );
      },
    ],
    [
      'an',
      ['ao', 'i', 'j'],
      function() {
        return new this.yy.Function(
          {
            filename: this.lexer.filename,
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
        );
      },
    ],
    [
      'aq',
      ['aq', 'g', 'as'],
      function() {
        this.$1.push(this.$3);
      },
    ],
    [
      'aq',
      ['as'],
      function() {
        return [this.$1];
      },
    ],
    ['as', ['ap']],
    ['ap', ['at']],
    [
      'ap',
      ['ad', 'au', 'ae'],
      function() {
        return new this.yy.ArrayExpression(this.$2);
      },
    ],
    [
      'ap',
      ['ad', 'ae'],
      function() {
        return new this.yy.ArrayExpression([]);
      },
    ],
    [
      'ap',
      ['af', 'av', 'ai'],
      function() {
        return new this.yy.ObjectExpression(this.$2);
      },
    ],
    [
      'ap',
      ['af', 'ai'],
      function() {
        return new this.yy.ObjectExpression([]);
      },
    ],
    [
      'aw',
      ['y', 'ag', 'ap'],
      function() {
        return [this.$1, this.$3];
      },
    ],
    [
      'aw',
      ['ab', 'ag', 'ap'],
      function() {
        return [this.$1, this.$3];
      },
    ],
    [
      'av',
      ['aw'],
      function() {
        return [this.$1];
      },
    ],
    [
      'av',
      ['av', 'g', 'aw'],
      function() {
        this.$1.push(this.$3);
      },
    ],
    [
      'au',
      ['ap'],
      function() {
        return [this.$1];
      },
    ],
    [
      'au',
      ['au', 'g', 'ap'],
      function() {
        this.$1.push(this.$3);
      },
    ],
    ['at', ['ax']],
    [
      'at',
      ['ax', 'ah', 'ax', 'ag', 'at'],
      function() {
        return new this.yy.ConditionalExpression(this.$1, this.$3, this.$5);
      },
    ],
    ['ax', ['ay']],
    [
      'ax',
      ['ax', 'k', 'ay'],
      function() {
        return new this.yy.ConditionalOrExpression(this.$1, this.$3);
      },
    ],
    ['ay', ['az']],
    [
      'ay',
      ['ay', 'l', 'az'],
      function() {
        return new this.yy.ConditionalAndExpression(this.$1, this.$3);
      },
    ],
    ['az', ['ba']],
    [
      'az',
      ['az', 'm', 'ba'],
      function() {
        return new this.yy.EqualityExpression(this.$1, '===', this.$3);
      },
    ],
    [
      'az',
      ['az', 'n', 'ba'],
      function() {
        return new this.yy.EqualityExpression(this.$1, '!==', this.$3);
      },
    ],
    ['ba', ['bb']],
    [
      'ba',
      ['ba', 'r', 'bb'],
      function() {
        return new this.yy.RelationalExpression(this.$1, '<', this.$3);
      },
    ],
    [
      'ba',
      ['ba', 'q', 'bb'],
      function() {
        return new this.yy.RelationalExpression(this.$1, '>', this.$3);
      },
    ],
    [
      'ba',
      ['ba', 'p', 'bb'],
      function() {
        return new this.yy.RelationalExpression(this.$1, '<=', this.$3);
      },
    ],
    [
      'ba',
      ['ba', 'o', 'bb'],
      function() {
        return new this.yy.RelationalExpression(this.$1, '>=', this.$3);
      },
    ],
    ['bb', ['bc']],
    [
      'bb',
      ['bb', 's', 'bc'],
      function() {
        return new this.yy.AdditiveExpression(this.$1, '+', this.$3);
      },
    ],
    [
      'bb',
      ['bb', 't', 'bc'],
      function() {
        return new this.yy.AdditiveExpression(this.$1, '-', this.$3);
      },
    ],
    ['bc', ['bd']],
    [
      'bc',
      ['bc', 'u', 'bd'],
      function() {
        return new this.yy.MultiplicativeExpression(this.$1, '*', this.$3);
      },
    ],
    [
      'bc',
      ['bc', 'v', 'bd'],
      function() {
        return new this.yy.MultiplicativeExpression(this.$1, '/', this.$3);
      },
    ],
    [
      'bc',
      ['bc', 'w', 'bd'],
      function() {
        return new this.yy.MultiplicativeExpression(this.$1, '%', this.$3);
      },
    ],
    [
      'bd',
      ['x', 'bd'],
      function() {
        return new this.yy.UnaryExpression(this.$1, this.$2);
      },
    ],
    [
      'bd',
      ['t', 'bd'],
      function() {
        return new this.yy.UnaryExpression(this.$1, this.$2);
      },
    ],
    ['bd', ['be']],
    [
      'be',
      ['y'],
      function() {
        return new this.yy.String(
          {
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
        );
      },
    ],
    [
      'be',
      ['z'],
      function() {
        return new this.yy.Number(
          {
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
        );
      },
    ],
    ['be', ['ao']],
    [
      'be',
      ['i', 'ap', 'j'],
      function() {
        return this.$2;
      },
    ],
    [
      'ar',
      ['ar', 'g', 'bf'],
      function() {
        this.$1.value.push(this.$3);
      },
    ],
    [
      'ar',
      ['bf'],
      function() {
        return new this.yy.Hash(
          {
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          [this.$1],
        );
      },
    ],
    [
      'bf',
      ['ao', 'aa', 'ap'],
      function() {
        return [this.$1, this.$3];
      },
    ],
    [
      'ao',
      ['bg'],
      function() {
        return new this.yy.Id(
          {
            line: this.lexer.firstLine,
            col: this.lexer.firstColumn,
          },
          this.$1,
        );
      },
    ],
    [
      'bg',
      ['an'],
      function() {
        return [this.$1];
      },
    ],
    [
      'bg',
      ['bg', 'ac', 'ab'],
      function() {
        this.$1.push(this.$3);
      },
    ],
    [
      'bg',
      ['bg', 'ad', 'ap', 'ae'],
      function() {
        this.$1.push(this.$3);
      },
    ],
    [
      'bg',
      ['ab'],
      function() {
        return [this.$1];
      },
    ],
  ];
  parser.table = {
    gotos: {
      '0': {
        ak: 4,
        al: 5,
        am: 6,
      },
      '2': {
        an: 8,
        ao: 9,
        bg: 10,
      },
      '3': {
        an: 18,
        ao: 19,
        ap: 20,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '5': { am: 31 },
      '11': {
        an: 18,
        ao: 19,
        ap: 36,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '12': {
        an: 18,
        ao: 19,
        bd: 37,
        be: 29,
        bg: 10,
      },
      '13': {
        an: 18,
        ao: 19,
        bd: 38,
        be: 29,
        bg: 10,
      },
      '16': {
        an: 18,
        ao: 19,
        ap: 40,
        at: 21,
        au: 41,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '17': {
        av: 45,
        aw: 46,
      },
      '30': {
        al: 62,
        am: 6,
      },
      '32': {
        ak: 63,
        al: 5,
        am: 6,
      },
      '33': {
        an: 18,
        ao: 65,
        ap: 66,
        aq: 67,
        ar: 68,
        as: 69,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bf: 70,
        bg: 10,
      },
      '35': {
        an: 18,
        ao: 19,
        ap: 72,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '48': {
        an: 18,
        ao: 19,
        ay: 80,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '49': {
        an: 18,
        ao: 19,
        ax: 81,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '50': {
        an: 18,
        ao: 19,
        az: 82,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '51': {
        an: 18,
        ao: 19,
        ba: 83,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '52': {
        an: 18,
        ao: 19,
        ba: 84,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '53': {
        an: 18,
        ao: 19,
        bb: 85,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '54': {
        an: 18,
        ao: 19,
        bb: 86,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '55': {
        an: 18,
        ao: 19,
        bb: 87,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '56': {
        an: 18,
        ao: 19,
        bb: 88,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '57': {
        an: 18,
        ao: 19,
        bc: 89,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '58': {
        an: 18,
        ao: 19,
        bc: 90,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '59': {
        an: 18,
        ao: 19,
        bd: 91,
        be: 29,
        bg: 10,
      },
      '60': {
        an: 18,
        ao: 19,
        bd: 92,
        be: 29,
        bg: 10,
      },
      '61': {
        an: 18,
        ao: 19,
        bd: 93,
        be: 29,
        bg: 10,
      },
      '62': { am: 31 },
      '74': {
        an: 18,
        ao: 19,
        ap: 101,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '76': {
        an: 18,
        ao: 19,
        ap: 102,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '77': {
        an: 18,
        ao: 19,
        ap: 103,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '78': { aw: 104 },
      '94': {
        an: 18,
        ao: 106,
        bg: 10,
      },
      '95': {
        an: 18,
        ao: 19,
        ap: 107,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
      '96': {
        an: 18,
        ao: 65,
        ap: 66,
        ar: 108,
        as: 109,
        at: 21,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bf: 70,
        bg: 10,
      },
      '98': {
        an: 18,
        ao: 110,
        bf: 111,
        bg: 10,
      },
      '105': {
        an: 18,
        ao: 19,
        at: 112,
        ax: 22,
        ay: 23,
        az: 24,
        ba: 25,
        bb: 26,
        bc: 27,
        bd: 28,
        be: 29,
        bg: 10,
      },
    },
    action: {
      '0': {
        b: [1, undefined, 1],
        c: [1, undefined, 2],
        f: [1, undefined, 3],
      },
      '1': {
        a: [2, 7],
        e: [2, 7],
        c: [2, 7],
        f: [2, 7],
        b: [2, 7],
        d: [2, 7],
      },
      '2': {
        ab: [1, undefined, 7],
      },
      '3': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '4': { a: [0] },
      '5': {
        a: [2, 2],
        d: [2, 2],
        b: [1, undefined, 1],
        c: [1, undefined, 2],
        e: [1, undefined, 30],
        f: [1, undefined, 3],
      },
      '6': {
        a: [2, 3],
        e: [2, 3],
        c: [2, 3],
        f: [2, 3],
        b: [2, 3],
        d: [2, 3],
      },
      '7': {
        i: [2, 61],
        ac: [2, 61],
        ad: [2, 61],
        h: [2, 61],
        ah: [2, 61],
        k: [2, 61],
        l: [2, 61],
        m: [2, 61],
        n: [2, 61],
        o: [2, 61],
        p: [2, 61],
        q: [2, 61],
        r: [2, 61],
        s: [2, 61],
        t: [2, 61],
        u: [2, 61],
        v: [2, 61],
        w: [2, 61],
        j: [2, 61],
        ae: [2, 61],
        g: [2, 61],
        aa: [2, 61],
        ag: [2, 61],
        ai: [2, 61],
      },
      '8': {
        i: [2, 58],
        ac: [2, 58],
        ad: [2, 58],
        h: [1, undefined, 32],
      },
      '9': {
        i: [1, undefined, 33],
      },
      '10': {
        i: [2, 57],
        h: [2, 57],
        ah: [2, 57],
        k: [2, 57],
        l: [2, 57],
        m: [2, 57],
        n: [2, 57],
        o: [2, 57],
        p: [2, 57],
        q: [2, 57],
        r: [2, 57],
        s: [2, 57],
        t: [2, 57],
        u: [2, 57],
        v: [2, 57],
        w: [2, 57],
        j: [2, 57],
        ae: [2, 57],
        g: [2, 57],
        aa: [2, 57],
        ag: [2, 57],
        ai: [2, 57],
        ac: [1, undefined, 34],
        ad: [1, undefined, 35],
      },
      '11': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '12': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '13': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '14': {
        h: [2, 50],
        ah: [2, 50],
        k: [2, 50],
        l: [2, 50],
        m: [2, 50],
        n: [2, 50],
        o: [2, 50],
        p: [2, 50],
        q: [2, 50],
        r: [2, 50],
        s: [2, 50],
        t: [2, 50],
        u: [2, 50],
        v: [2, 50],
        w: [2, 50],
        j: [2, 50],
        ae: [2, 50],
        g: [2, 50],
        ag: [2, 50],
        ai: [2, 50],
      },
      '15': {
        h: [2, 51],
        ah: [2, 51],
        k: [2, 51],
        l: [2, 51],
        m: [2, 51],
        n: [2, 51],
        o: [2, 51],
        p: [2, 51],
        q: [2, 51],
        r: [2, 51],
        s: [2, 51],
        t: [2, 51],
        u: [2, 51],
        v: [2, 51],
        w: [2, 51],
        j: [2, 51],
        ae: [2, 51],
        g: [2, 51],
        ag: [2, 51],
        ai: [2, 51],
      },
      '16': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        ae: [1, undefined, 39],
        af: [1, undefined, 17],
      },
      '17': {
        y: [1, undefined, 42],
        ab: [1, undefined, 43],
        ai: [1, undefined, 44],
      },
      '18': {
        h: [2, 58],
        ah: [2, 58],
        i: [2, 58],
        k: [2, 58],
        l: [2, 58],
        m: [2, 58],
        n: [2, 58],
        o: [2, 58],
        p: [2, 58],
        q: [2, 58],
        r: [2, 58],
        s: [2, 58],
        t: [2, 58],
        u: [2, 58],
        v: [2, 58],
        w: [2, 58],
        ac: [2, 58],
        ad: [2, 58],
        j: [2, 58],
        ae: [2, 58],
        g: [2, 58],
        aa: [2, 58],
        ag: [2, 58],
        ai: [2, 58],
      },
      '19': {
        h: [2, 52],
        ah: [2, 52],
        k: [2, 52],
        l: [2, 52],
        m: [2, 52],
        n: [2, 52],
        o: [2, 52],
        p: [2, 52],
        q: [2, 52],
        r: [2, 52],
        s: [2, 52],
        t: [2, 52],
        u: [2, 52],
        v: [2, 52],
        w: [2, 52],
        j: [2, 52],
        ae: [2, 52],
        g: [2, 52],
        ag: [2, 52],
        ai: [2, 52],
        i: [1, undefined, 33],
      },
      '20': {
        h: [1, undefined, 47],
      },
      '21': {
        h: [2, 15],
        j: [2, 15],
        ae: [2, 15],
        g: [2, 15],
        ai: [2, 15],
      },
      '22': {
        h: [2, 26],
        j: [2, 26],
        ae: [2, 26],
        g: [2, 26],
        ai: [2, 26],
        k: [1, undefined, 48],
        ah: [1, undefined, 49],
      },
      '23': {
        h: [2, 28],
        ah: [2, 28],
        k: [2, 28],
        j: [2, 28],
        ae: [2, 28],
        g: [2, 28],
        ag: [2, 28],
        ai: [2, 28],
        l: [1, undefined, 50],
      },
      '24': {
        h: [2, 30],
        ah: [2, 30],
        k: [2, 30],
        l: [2, 30],
        j: [2, 30],
        ae: [2, 30],
        g: [2, 30],
        ag: [2, 30],
        ai: [2, 30],
        m: [1, undefined, 51],
        n: [1, undefined, 52],
      },
      '25': {
        h: [2, 32],
        ah: [2, 32],
        k: [2, 32],
        l: [2, 32],
        m: [2, 32],
        n: [2, 32],
        j: [2, 32],
        ae: [2, 32],
        g: [2, 32],
        ag: [2, 32],
        ai: [2, 32],
        o: [1, undefined, 53],
        p: [1, undefined, 54],
        q: [1, undefined, 55],
        r: [1, undefined, 56],
      },
      '26': {
        h: [2, 35],
        ah: [2, 35],
        k: [2, 35],
        l: [2, 35],
        m: [2, 35],
        n: [2, 35],
        o: [2, 35],
        p: [2, 35],
        q: [2, 35],
        r: [2, 35],
        j: [2, 35],
        ae: [2, 35],
        g: [2, 35],
        ag: [2, 35],
        ai: [2, 35],
        s: [1, undefined, 57],
        t: [1, undefined, 58],
      },
      '27': {
        h: [2, 40],
        ah: [2, 40],
        k: [2, 40],
        l: [2, 40],
        m: [2, 40],
        n: [2, 40],
        o: [2, 40],
        p: [2, 40],
        q: [2, 40],
        r: [2, 40],
        s: [2, 40],
        t: [2, 40],
        j: [2, 40],
        ae: [2, 40],
        g: [2, 40],
        ag: [2, 40],
        ai: [2, 40],
        u: [1, undefined, 59],
        v: [1, undefined, 60],
        w: [1, undefined, 61],
      },
      '28': {
        h: [2, 43],
        ah: [2, 43],
        k: [2, 43],
        l: [2, 43],
        m: [2, 43],
        n: [2, 43],
        o: [2, 43],
        p: [2, 43],
        q: [2, 43],
        r: [2, 43],
        s: [2, 43],
        t: [2, 43],
        u: [2, 43],
        v: [2, 43],
        w: [2, 43],
        j: [2, 43],
        ae: [2, 43],
        g: [2, 43],
        ag: [2, 43],
        ai: [2, 43],
      },
      '29': {
        h: [2, 49],
        ah: [2, 49],
        k: [2, 49],
        l: [2, 49],
        m: [2, 49],
        n: [2, 49],
        o: [2, 49],
        p: [2, 49],
        q: [2, 49],
        r: [2, 49],
        s: [2, 49],
        t: [2, 49],
        u: [2, 49],
        v: [2, 49],
        w: [2, 49],
        j: [2, 49],
        ae: [2, 49],
        g: [2, 49],
        ag: [2, 49],
        ai: [2, 49],
      },
      '30': {
        b: [1, undefined, 1],
        c: [1, undefined, 2],
        f: [1, undefined, 3],
      },
      '31': {
        a: [2, 4],
        e: [2, 4],
        c: [2, 4],
        f: [2, 4],
        b: [2, 4],
        d: [2, 4],
      },
      '32': {
        b: [1, undefined, 1],
        c: [1, undefined, 2],
        f: [1, undefined, 3],
      },
      '33': {
        i: [1, undefined, 11],
        j: [1, undefined, 64],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '34': {
        ab: [1, undefined, 71],
      },
      '35': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '36': {
        j: [1, undefined, 73],
      },
      '37': {
        h: [2, 48],
        ah: [2, 48],
        k: [2, 48],
        l: [2, 48],
        m: [2, 48],
        n: [2, 48],
        o: [2, 48],
        p: [2, 48],
        q: [2, 48],
        r: [2, 48],
        s: [2, 48],
        t: [2, 48],
        u: [2, 48],
        v: [2, 48],
        w: [2, 48],
        j: [2, 48],
        ae: [2, 48],
        g: [2, 48],
        ag: [2, 48],
        ai: [2, 48],
      },
      '38': {
        h: [2, 47],
        ah: [2, 47],
        k: [2, 47],
        l: [2, 47],
        m: [2, 47],
        n: [2, 47],
        o: [2, 47],
        p: [2, 47],
        q: [2, 47],
        r: [2, 47],
        s: [2, 47],
        t: [2, 47],
        u: [2, 47],
        v: [2, 47],
        w: [2, 47],
        j: [2, 47],
        ae: [2, 47],
        g: [2, 47],
        ag: [2, 47],
        ai: [2, 47],
      },
      '39': {
        h: [2, 17],
        j: [2, 17],
        ae: [2, 17],
        g: [2, 17],
        ai: [2, 17],
      },
      '40': {
        ae: [2, 24],
        g: [2, 24],
      },
      '41': {
        g: [1, undefined, 74],
        ae: [1, undefined, 75],
      },
      '42': {
        ag: [1, undefined, 76],
      },
      '43': {
        ag: [1, undefined, 77],
      },
      '44': {
        h: [2, 19],
        j: [2, 19],
        ae: [2, 19],
        g: [2, 19],
        ai: [2, 19],
      },
      '45': {
        g: [1, undefined, 78],
        ai: [1, undefined, 79],
      },
      '46': {
        ai: [2, 22],
        g: [2, 22],
      },
      '47': {
        a: [2, 6],
        e: [2, 6],
        c: [2, 6],
        f: [2, 6],
        b: [2, 6],
        d: [2, 6],
      },
      '48': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '49': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '50': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '51': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '52': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '53': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '54': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '55': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '56': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '57': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '58': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '59': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '60': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '61': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '62': {
        a: [2, 1],
        d: [2, 1],
        b: [1, undefined, 1],
        c: [1, undefined, 2],
        f: [1, undefined, 3],
      },
      '63': {
        d: [1, undefined, 94],
      },
      '64': {
        h: [2, 11],
        i: [2, 11],
        ac: [2, 11],
        ad: [2, 11],
        ah: [2, 11],
        k: [2, 11],
        l: [2, 11],
        m: [2, 11],
        n: [2, 11],
        o: [2, 11],
        p: [2, 11],
        q: [2, 11],
        r: [2, 11],
        s: [2, 11],
        t: [2, 11],
        u: [2, 11],
        v: [2, 11],
        w: [2, 11],
        j: [2, 11],
        ae: [2, 11],
        g: [2, 11],
        aa: [2, 11],
        ag: [2, 11],
        ai: [2, 11],
      },
      '65': {
        g: [2, 52],
        j: [2, 52],
        ah: [2, 52],
        k: [2, 52],
        l: [2, 52],
        m: [2, 52],
        n: [2, 52],
        o: [2, 52],
        p: [2, 52],
        q: [2, 52],
        r: [2, 52],
        s: [2, 52],
        t: [2, 52],
        u: [2, 52],
        v: [2, 52],
        w: [2, 52],
        i: [1, undefined, 33],
        aa: [1, undefined, 95],
      },
      '66': {
        g: [2, 14],
        j: [2, 14],
      },
      '67': {
        g: [1, undefined, 96],
        j: [1, undefined, 97],
      },
      '68': {
        g: [1, undefined, 98],
        j: [1, undefined, 99],
      },
      '69': {
        g: [2, 13],
        j: [2, 13],
      },
      '70': {
        j: [2, 55],
        g: [2, 55],
      },
      '71': {
        i: [2, 59],
        ac: [2, 59],
        ad: [2, 59],
        h: [2, 59],
        ah: [2, 59],
        k: [2, 59],
        l: [2, 59],
        m: [2, 59],
        n: [2, 59],
        o: [2, 59],
        p: [2, 59],
        q: [2, 59],
        r: [2, 59],
        s: [2, 59],
        t: [2, 59],
        u: [2, 59],
        v: [2, 59],
        w: [2, 59],
        j: [2, 59],
        ae: [2, 59],
        g: [2, 59],
        aa: [2, 59],
        ag: [2, 59],
        ai: [2, 59],
      },
      '72': {
        ae: [1, undefined, 100],
      },
      '73': {
        h: [2, 53],
        ah: [2, 53],
        k: [2, 53],
        l: [2, 53],
        m: [2, 53],
        n: [2, 53],
        o: [2, 53],
        p: [2, 53],
        q: [2, 53],
        r: [2, 53],
        s: [2, 53],
        t: [2, 53],
        u: [2, 53],
        v: [2, 53],
        w: [2, 53],
        j: [2, 53],
        ae: [2, 53],
        g: [2, 53],
        ag: [2, 53],
        ai: [2, 53],
      },
      '74': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '75': {
        h: [2, 16],
        j: [2, 16],
        ae: [2, 16],
        g: [2, 16],
        ai: [2, 16],
      },
      '76': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '77': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '78': {
        y: [1, undefined, 42],
        ab: [1, undefined, 43],
      },
      '79': {
        h: [2, 18],
        j: [2, 18],
        ae: [2, 18],
        g: [2, 18],
        ai: [2, 18],
      },
      '80': {
        h: [2, 29],
        ah: [2, 29],
        k: [2, 29],
        j: [2, 29],
        ae: [2, 29],
        g: [2, 29],
        ag: [2, 29],
        ai: [2, 29],
        l: [1, undefined, 50],
      },
      '81': {
        k: [1, undefined, 48],
        ag: [1, undefined, 105],
      },
      '82': {
        h: [2, 31],
        ah: [2, 31],
        k: [2, 31],
        l: [2, 31],
        j: [2, 31],
        ae: [2, 31],
        g: [2, 31],
        ag: [2, 31],
        ai: [2, 31],
        m: [1, undefined, 51],
        n: [1, undefined, 52],
      },
      '83': {
        h: [2, 33],
        ah: [2, 33],
        k: [2, 33],
        l: [2, 33],
        m: [2, 33],
        n: [2, 33],
        j: [2, 33],
        ae: [2, 33],
        g: [2, 33],
        ag: [2, 33],
        ai: [2, 33],
        o: [1, undefined, 53],
        p: [1, undefined, 54],
        q: [1, undefined, 55],
        r: [1, undefined, 56],
      },
      '84': {
        h: [2, 34],
        ah: [2, 34],
        k: [2, 34],
        l: [2, 34],
        m: [2, 34],
        n: [2, 34],
        j: [2, 34],
        ae: [2, 34],
        g: [2, 34],
        ag: [2, 34],
        ai: [2, 34],
        o: [1, undefined, 53],
        p: [1, undefined, 54],
        q: [1, undefined, 55],
        r: [1, undefined, 56],
      },
      '85': {
        h: [2, 39],
        ah: [2, 39],
        k: [2, 39],
        l: [2, 39],
        m: [2, 39],
        n: [2, 39],
        o: [2, 39],
        p: [2, 39],
        q: [2, 39],
        r: [2, 39],
        j: [2, 39],
        ae: [2, 39],
        g: [2, 39],
        ag: [2, 39],
        ai: [2, 39],
        s: [1, undefined, 57],
        t: [1, undefined, 58],
      },
      '86': {
        h: [2, 38],
        ah: [2, 38],
        k: [2, 38],
        l: [2, 38],
        m: [2, 38],
        n: [2, 38],
        o: [2, 38],
        p: [2, 38],
        q: [2, 38],
        r: [2, 38],
        j: [2, 38],
        ae: [2, 38],
        g: [2, 38],
        ag: [2, 38],
        ai: [2, 38],
        s: [1, undefined, 57],
        t: [1, undefined, 58],
      },
      '87': {
        h: [2, 37],
        ah: [2, 37],
        k: [2, 37],
        l: [2, 37],
        m: [2, 37],
        n: [2, 37],
        o: [2, 37],
        p: [2, 37],
        q: [2, 37],
        r: [2, 37],
        j: [2, 37],
        ae: [2, 37],
        g: [2, 37],
        ag: [2, 37],
        ai: [2, 37],
        s: [1, undefined, 57],
        t: [1, undefined, 58],
      },
      '88': {
        h: [2, 36],
        ah: [2, 36],
        k: [2, 36],
        l: [2, 36],
        m: [2, 36],
        n: [2, 36],
        o: [2, 36],
        p: [2, 36],
        q: [2, 36],
        r: [2, 36],
        j: [2, 36],
        ae: [2, 36],
        g: [2, 36],
        ag: [2, 36],
        ai: [2, 36],
        s: [1, undefined, 57],
        t: [1, undefined, 58],
      },
      '89': {
        h: [2, 41],
        ah: [2, 41],
        k: [2, 41],
        l: [2, 41],
        m: [2, 41],
        n: [2, 41],
        o: [2, 41],
        p: [2, 41],
        q: [2, 41],
        r: [2, 41],
        s: [2, 41],
        t: [2, 41],
        j: [2, 41],
        ae: [2, 41],
        g: [2, 41],
        ag: [2, 41],
        ai: [2, 41],
        u: [1, undefined, 59],
        v: [1, undefined, 60],
        w: [1, undefined, 61],
      },
      '90': {
        h: [2, 42],
        ah: [2, 42],
        k: [2, 42],
        l: [2, 42],
        m: [2, 42],
        n: [2, 42],
        o: [2, 42],
        p: [2, 42],
        q: [2, 42],
        r: [2, 42],
        s: [2, 42],
        t: [2, 42],
        j: [2, 42],
        ae: [2, 42],
        g: [2, 42],
        ag: [2, 42],
        ai: [2, 42],
        u: [1, undefined, 59],
        v: [1, undefined, 60],
        w: [1, undefined, 61],
      },
      '91': {
        h: [2, 44],
        ah: [2, 44],
        k: [2, 44],
        l: [2, 44],
        m: [2, 44],
        n: [2, 44],
        o: [2, 44],
        p: [2, 44],
        q: [2, 44],
        r: [2, 44],
        s: [2, 44],
        t: [2, 44],
        u: [2, 44],
        v: [2, 44],
        w: [2, 44],
        j: [2, 44],
        ae: [2, 44],
        g: [2, 44],
        ag: [2, 44],
        ai: [2, 44],
      },
      '92': {
        h: [2, 45],
        ah: [2, 45],
        k: [2, 45],
        l: [2, 45],
        m: [2, 45],
        n: [2, 45],
        o: [2, 45],
        p: [2, 45],
        q: [2, 45],
        r: [2, 45],
        s: [2, 45],
        t: [2, 45],
        u: [2, 45],
        v: [2, 45],
        w: [2, 45],
        j: [2, 45],
        ae: [2, 45],
        g: [2, 45],
        ag: [2, 45],
        ai: [2, 45],
      },
      '93': {
        h: [2, 46],
        ah: [2, 46],
        k: [2, 46],
        l: [2, 46],
        m: [2, 46],
        n: [2, 46],
        o: [2, 46],
        p: [2, 46],
        q: [2, 46],
        r: [2, 46],
        s: [2, 46],
        t: [2, 46],
        u: [2, 46],
        v: [2, 46],
        w: [2, 46],
        j: [2, 46],
        ae: [2, 46],
        g: [2, 46],
        ag: [2, 46],
        ai: [2, 46],
      },
      '94': {
        ab: [1, undefined, 7],
      },
      '95': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '96': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
        ad: [1, undefined, 16],
        af: [1, undefined, 17],
      },
      '97': {
        h: [2, 9],
        i: [2, 9],
        ac: [2, 9],
        ad: [2, 9],
        ah: [2, 9],
        k: [2, 9],
        l: [2, 9],
        m: [2, 9],
        n: [2, 9],
        o: [2, 9],
        p: [2, 9],
        q: [2, 9],
        r: [2, 9],
        s: [2, 9],
        t: [2, 9],
        u: [2, 9],
        v: [2, 9],
        w: [2, 9],
        j: [2, 9],
        ae: [2, 9],
        g: [2, 9],
        aa: [2, 9],
        ag: [2, 9],
        ai: [2, 9],
      },
      '98': {
        ab: [1, undefined, 7],
      },
      '99': {
        h: [2, 10],
        i: [2, 10],
        ac: [2, 10],
        ad: [2, 10],
        ah: [2, 10],
        k: [2, 10],
        l: [2, 10],
        m: [2, 10],
        n: [2, 10],
        o: [2, 10],
        p: [2, 10],
        q: [2, 10],
        r: [2, 10],
        s: [2, 10],
        t: [2, 10],
        u: [2, 10],
        v: [2, 10],
        w: [2, 10],
        j: [2, 10],
        ae: [2, 10],
        g: [2, 10],
        aa: [2, 10],
        ag: [2, 10],
        ai: [2, 10],
      },
      '100': {
        i: [2, 60],
        ac: [2, 60],
        ad: [2, 60],
        h: [2, 60],
        ah: [2, 60],
        k: [2, 60],
        l: [2, 60],
        m: [2, 60],
        n: [2, 60],
        o: [2, 60],
        p: [2, 60],
        q: [2, 60],
        r: [2, 60],
        s: [2, 60],
        t: [2, 60],
        u: [2, 60],
        v: [2, 60],
        w: [2, 60],
        j: [2, 60],
        ae: [2, 60],
        g: [2, 60],
        aa: [2, 60],
        ag: [2, 60],
        ai: [2, 60],
      },
      '101': {
        ae: [2, 25],
        g: [2, 25],
      },
      '102': {
        ai: [2, 20],
        g: [2, 20],
      },
      '103': {
        ai: [2, 21],
        g: [2, 21],
      },
      '104': {
        ai: [2, 23],
        g: [2, 23],
      },
      '105': {
        i: [1, undefined, 11],
        t: [1, undefined, 12],
        x: [1, undefined, 13],
        y: [1, undefined, 14],
        z: [1, undefined, 15],
        ab: [1, undefined, 7],
      },
      '106': {
        h: [1, undefined, 113],
        i: [1, undefined, 33],
      },
      '107': {
        j: [2, 56],
        g: [2, 56],
      },
      '108': {
        g: [1, undefined, 98],
        j: [1, undefined, 114],
      },
      '109': {
        g: [2, 12],
        j: [2, 12],
      },
      '110': {
        i: [1, undefined, 33],
        aa: [1, undefined, 95],
      },
      '111': {
        j: [2, 54],
        g: [2, 54],
      },
      '112': {
        h: [2, 27],
        j: [2, 27],
        ae: [2, 27],
        g: [2, 27],
        ai: [2, 27],
      },
      '113': {
        a: [2, 5],
        e: [2, 5],
        c: [2, 5],
        f: [2, 5],
        b: [2, 5],
        d: [2, 5],
      },
      '114': {
        h: [2, 8],
        i: [2, 8],
        ac: [2, 8],
        ad: [2, 8],
        ah: [2, 8],
        k: [2, 8],
        l: [2, 8],
        m: [2, 8],
        n: [2, 8],
        o: [2, 8],
        p: [2, 8],
        q: [2, 8],
        r: [2, 8],
        s: [2, 8],
        t: [2, 8],
        u: [2, 8],
        v: [2, 8],
        w: [2, 8],
        j: [2, 8],
        ae: [2, 8],
        g: [2, 8],
        aa: [2, 8],
        ag: [2, 8],
        ai: [2, 8],
      },
    },
  };
  parser.parse = function parse(input, filename) {
    var state, symbol, ret, action, $$;
    var self = this;
    var lexer = self.lexer;
    var table = self.table;
    var gotos = table.gotos;
    var tableAction = table.action;
    var productions = self.productions; // for debug info
    // for debug info
    var prefix = filename ? 'in file: ' + filename + ' ' : '';
    var valueStack = [];
    var stateStack = [0];
    var symbolStack = [];
    lexer.resetInput(input);
    while (1) {
      // retrieve state number from top of stack
      state = peekStack(stateStack);
      if (!symbol) {
        symbol = lexer.lex();
      }
      if (symbol) {
        // read action for current state and first input
        action = tableAction[state] && tableAction[state][symbol];
      } else {
        action = null;
      }
      if (!action) {
        var expected = [];
        var error; //#JSCOVERAGE_IF
        //#JSCOVERAGE_IF
        if (tableAction[state]) {
          each(tableAction[state], function(v, symbolForState) {
            action = v[GrammarConst.TYPE_INDEX];
            var map = [];
            map[GrammarConst.SHIFT_TYPE] = 'shift';
            map[GrammarConst.REDUCE_TYPE] = 'reduce';
            map[GrammarConst.ACCEPT_TYPE] = 'accept';
            expected.push(
              map[action] + ':' + self.lexer.mapReverseSymbol(symbolForState),
            );
          });
        }
        error =
          prefix +
          'syntax error at line ' +
          lexer.lineNumber +
          ':\n' +
          lexer.showDebugInfo() +
          '\n' +
          'expect ' +
          expected.join(', ');
        throw new Error(error);
      }
      switch (action[GrammarConst.TYPE_INDEX]) {
        case GrammarConst.SHIFT_TYPE:
          symbolStack.push(symbol);
          valueStack.push(lexer.text); // push state
          // push state
          stateStack.push(action[GrammarConst.TO_INDEX]); // allow to read more
          // allow to read more
          symbol = null;
          break;
        case GrammarConst.REDUCE_TYPE:
          var production = productions[action[GrammarConst.PRODUCTION_INDEX]];
          var reducedSymbol = production.symbol || production[0];
          var reducedAction = production.action || production[2];
          var reducedRhs = production.rhs || production[1];
          var len = reducedRhs.length;
          $$ = peekStack(valueStack, len); // default to $$ = $1
          // default to $$ = $1
          ret = undefined;
          self.$$ = $$;
          for (var i = 0; i < len; i++) {
            self['$' + (len - i)] = peekStack(valueStack, i + 1);
          }
          if (reducedAction) {
            ret = reducedAction.call(self);
          }
          if (ret !== undefined) {
            $$ = ret;
          } else {
            $$ = self.$$;
          }
          var reverseIndex = len * -1;
          stateStack.splice(reverseIndex, len);
          valueStack.splice(reverseIndex, len);
          symbolStack.splice(reverseIndex, len);
          symbolStack.push(reducedSymbol);
          valueStack.push($$);
          var newState = gotos[peekStack(stateStack)][reducedSymbol];
          stateStack.push(newState);
          break;
        case GrammarConst.ACCEPT_TYPE:
          return $$;
      }
    }
  };
  return parser;
})();
export default parser;
